<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mi Sitio en GitHub</title>
    <style>
        /* Estilos básicos para que se vea genial */
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            margin: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
            background-color: #f4f4f9;
            color: #333;
        }
        .container {
            max-width: 600px;
            padding: 2rem;
            background: white;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            border-radius: 10px;
            text-align: center;
        }
        h1 { color: #2ecc71; }
        p { font-size: 1.1rem; }
        .btn {
            display: inline-block;
            background: #333;
            color: white;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 5px;
            margin-top: 1rem;
            transition: background 0.3s;
        }
        .btn:hover { background: #555; }
    </style>
</head>
<body>

    <div class="container">
        <h1>¡Hola Mundo desde GitHub! 🚀</h1>
        <p>Esta es mi primera página web hospedada de forma gratuita en <strong>GitHub Pages</strong>.</p>
        <p>A partir de aquí, puedo empezar a construir mi portafolio o mi blog personal.</p>
        <a href="https://github.com" class="btn">Ver mi perfil</a>
    </div>

</body>
</index.html>
